### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by 894752114** [kuckboy1994/mp_canvas_drawer#1]
你好，我点击绘制之后，就一直显示绘制分享图片中 然后没有图片出来，是怎么回事啊，谢谢

**Comment by kuckboy1994** [comment]
@894752114  是当前项目clone到本地的吗？  
有没有改动，有没有报错信息？

**Comment by kuckboy1994** [comment]
@894752114 一个小时前修复了一个本地图片无法渲染的bug。不知道你是不是遇到了这个问题

**Comment by 894752114** [comment]
可以了 非常感谢
