### ISSUE TITLE
如何使用opendata里的头像和昵称

### ISSUE THREAD

**Issue by ALANXIAORUI** [kuckboy1994/mp_canvas_drawer#14]
如题，这两串官方代码都是在wxml里面用的啊，但你的绘制是在js完成，有啥办法用上：
    <open-data type="userAvatarUrl"></open-data>
    <open-data type="userNickName" lang="zh_CN"></open-data>

**Comment by ALANXIAORUI** [comment]
<open-data type="userAvatarUrl"></open-data>
    <open-data type="userNickName" lang="zh_CN"></open-data>

**Comment by duzzu** [comment]
估计需要getuserinfo一下
