### ISSUE TITLE
基于wepy的canvas_drawer组件

### ISSUE THREAD

**Issue by simmzl** [kuckboy1994/mp_canvas_drawer#19]
十分感谢你开发了原生组件以及mpvue版本的canvas_drawer！
根据你的代码，我移植开发了wepy版本，希望能加入您的文档里！
地址：[wepy_canvas_drawer](https://github.com/simmzl/wepy_canvas_drawer)

**Comment by kuckboy1994** [comment]
@simmzl  已添加
