### ISSUE TITLE
修复了安卓生成图片文字错位的bug。

### ISSUE THREAD

**Issue by qizf7** [kuckboy1994/mp_canvas_drawer#27]
提了pr给你，修复了安卓生成图片文字错位的bug。@kuckboy1994
https://github.com/qizf7/mp_canvas_drawer

**Comment by hgq520** [comment]
请问大神，安卓绘图为什么文字错乱啊

**Comment by qizf7** [comment]
@hgq520  安卓手机在.draw函数的回调中直接保存图片会出现错乱现象，应该是小程序的bug，调用draw回调函数时还没有绘制完图片，判断为安卓手机延迟保存就好了。

**Comment by hgq520** [comment]
我在安卓手机绘制的时候，我明明设置了别的字体和颜色，他却使用的是上次的颜色字体。看来绘图不一定按照代码执行顺序来的

**Comment by Veepim** [comment]
楼主你判断IOS设备那段代码中system没有定义啊

**Comment by qizf7** [comment]
@Veepim 
抱歉少写了一行，现在好了
https://github.com/qizf7/mp_canvas_drawer/blob/master/components/canvasdrawer/canvasdrawer.js

**Comment by renyuns** [comment]
**是这种吗,我的也是 android ### 手机会出现重叠,和设置了字体,颜色不管用**
![image](https://user-images.githubusercontent.com/22095724/45138027-9b86ed80-b1dd-11e8-9e95-3f1e9556d88d.png)

**Comment by renyuns** [comment]
![image](https://user-images.githubusercontent.com/22095724/45138096-d721b780-b1dd-11e8-88da-5285cddef49d.png)

**Comment by qizf7** [comment]
@renyuns 对的
