### ISSUE TITLE
type:'text'  , 文本的对齐方式失效？？？

### ISSUE THREAD

**Issue by Veepim** [kuckboy1994/mp_canvas_drawer#34]
`{
                        type: 'text',
                        content: 'this is text',
                        fontSize: 30,
                        color: '#402D16',
                        textAlign: 'center',
                        top: 270,
                        right: 0
                    },`

我设置文案居中或者居右的时候没有效果，只有居左的时候可以显示

**Comment by hopkinson** [comment]
我的也是

**Comment by kuckboy1994** [comment]
@Veepim textAlign 的实现就是按照最底层的api来的。你可以参看一下这个代码。
[CanvasContext.setTextAlign(string align)](https://developers.weixin.qq.com/miniprogram/dev/api/canvas/CanvasContext.setTextAlign.html)
