### ISSUE TITLE
关于换行

### ISSUE THREAD

**Issue by a294465800** [kuckboy1994/mp_canvas_drawer#4]
首先，你这个组件很棒！然后在一些使用场景里，是有对内容进行换行，但不作内容省略的（不管有多少字都继续换行），感觉可以出个配置参数做不省略处理。

**Comment by kuckboy1994** [comment]
谢谢你的赞赏。

其实当前配置是可以实现你的需求的，只要你把行数设置的足够大，例如：`100`。就达不到触发显示省略号的条件了。

**Comment by a294465800** [comment]
good！
