### ISSUE TITLE
预览的时候在真机上，安卓和IOS都无法正常绘制，但是打开了调试模式之后，又可以正常的绘制成功！

### ISSUE THREAD

**Issue by zyxyuanxiao** [kuckboy1994/mp_canvas_drawer#46]

**Comment by shanjixiaboss** [comment]
是不是微信头像？需要添加安全域名

**Comment by zhanligui** [comment]
你解决了吗  我的也不行

**Comment by shanjixiaboss** [comment]
canvasdrawer.js在232行左右，检查getImageInfo中每个url的域名是否合法

**Comment by zhanligui** [comment]
把域名的正则改了一下后 文字能出来 但图片出不来  层级也有问题

**Comment by shanjixiaboss** [comment]
如果没有提供相关api，只能按照push层级来了，我是在图片下面的最后push进去


| |
陈冲
|
|
shanjixiaboss@163.com
|
签名由网易邮箱大师定制
在2018年10月31日 14:25，zhanligui<notifications@github.com> 写道：

就差层级问题了

**Comment by yizenghui** [comment]
关闭 不校验合法域名、web-view（业务域名）、TLS 版本以及 HTTPS 证书 可以得到错误
