### ISSUE TITLE
圆形头像可以用 canvasContext.clip 啊

### ISSUE THREAD

**Issue by duminghong** [kuckboy1994/mp_canvas_drawer#5]
[canvasContext.clip](https://developers.weixin.qq.com/miniprogram/dev/api/canvas/clip.html)

**Comment by kuckboy1994** [comment]
感谢提醒。

主要是现在 `clip` 方法还存在 `bug`。见 [微信开发者社区，bug反馈](https://developers.weixin.qq.com/blogdetail?action=get_post_info&docid=00086255ef09d0df4b0751f6651000&highline=clip&token=895863755&lang=zh_CN)。`rect` 和 `clip` 不能同时共存。当前组件也提供了 `rect` 的绘制方法，可能会有影响。圆形的话，也已经提供了解决的方法，个人感觉也不是不能接受。

你认为如何？

**Comment by duminghong** [comment]
这个bug真机是没问题的，只是开发者工具有问题，很早之前我就用过
> rect 和 clip 不能同时共存

这个我还没遇到过，因为如果用遮罩中间透明的图成本比较高，得专门切图，如果是渐变背景有可能会对不上
___当然我只是提建议___ ( ^_^ )

**Comment by kuckboy1994** [comment]
刚才我又试了一下，微信小程序中 `rect` 相关的接口调用之后，使用 `clip` 之后，开发工具显示为矩形，真机直接无法显示了。

> 这个我还没遇到过，因为如果用遮罩中间透明的图成本比较高，得专门切图，如果是渐变背景有可能会对不上

对于你说的这个切图成本的话，如果是公司的话，应该可以让ui做一下，个人就比较。。。

我当前栗子中给的就是类似的渐变的（不是同色的），量好距离应该是完全无缝的。

接下去应该不会准备去支持圆形头像了。除非微信官方 `api` 能修改这个bug
