### ISSUE TITLE
建议可以给图片增加圆角属性

### ISSUE THREAD

**Issue by JustPlayN** [kuckboy1994/mp_canvas_drawer#7]

**Comment by CPPAlien** [comment]
这个不可抗拒的问题是由于代码实现的问题，有兴趣的话，可以看看 painter 的实现，painter 相对完美的解决了圆角问题。当然有兴趣的话，也欢迎一起交流小程序的图片生成实现。:) 。

**Comment by kuckboy1994** [comment]
@CPPAlien  谢谢指出，接下去会修改一下。

**Comment by CPPAlien** [comment]
要不你直接用 Painter 得了，目前来说，你这个库得所有实现都可以用 Painter 做到，https://github.com/Kujiale-Mobile/Painter ，也无文字重叠这些问题。mpvue 的使用我们近期也会出相关接入文档。

**Comment by JustPlayN** [comment]
@CPPAlien thanks
