### ISSUE TITLE
希望增加对QQ小程序的支持

### ISSUE THREAD

**Issue by Airmole** [kuckboy1994/mp_canvas_drawer#84]
经过实践，大多数微信小程序的项目代码直接放在QQ小程序里也可以跑起来，但是mp_canvas_drawer在运行时有一个js报错，感觉应该不是很难改。用箭头函数或许可以解决。希望能够更新解决一下。

**Comment by bianyukun1213** [comment]
我没有遇到报错，QQ小程序版可以正常运行。

**Comment by Airmole** [comment]
> 我没有遇到报错，QQ小程序版可以正常运行。

好吧，那可能是我自己环境的问题吧。我再试试。谢谢你啦
